name: Deploy API with Publish Profile

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'api/**'
      - '.github/workflows/deploy-api-publishprofile.yml'

jobs:
  deploy:
    runs-on: windows-latest
    name: Deploy API using Publish Profile
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: api
        
      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: api
        
      - name: Publish
        run: dotnet publish SqlAnalyzer.Api/SqlAnalyzer.Api.csproj -c Release -o ./publish
        working-directory: api
        
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: sqlanalyzer-api-win
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: api/publish