name: Deploy API to Azure App Service

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'api/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy API
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: api
        
      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: api
        
      - name: Publish
        run: dotnet publish SqlAnalyzer.Api/SqlAnalyzer.Api.csproj -c Release -o ./publish
        working-directory: api
        
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: sqlanalyzer-api-v2
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: api/publish
