name: Deploy API to Azure App Service

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy API
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: api
        
      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: api
        
      - name: Publish
        run: dotnet publish SqlAnalyzer.Api/SqlAnalyzer.Api.csproj -c Release -o ./publish
        working-directory: api
        
      - name: Get current time
        id: current-time
        run: echo "time=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT
        
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: sqlanalyzer-api-win
          package: api/publish
        env:
          BUILD_TIMESTAMP: ${{ steps.current-time.outputs.time }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
